_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: "all"

scenario_types: null
scenario_tokens: null
 
log_names:
 - 2021.06.07.11.59.52_veh-35_00095_00555
 - 2021.10.22.18.45.52_veh-28_00313_00628
 - 2021.09.10.13.55.04_veh-39_00816_00959
 - 2021.10.22.18.45.52_veh-28_01175_01298
 - 2021.10.22.18.02.31_veh-28_01717_02099


map_names: null

num_scenarios_per_type: null
limit_total_scenarios: 20
timestamp_threshold_s: 15
ego_displacement_minimum_m: null # Whether to remove scenarios where the ego moves less than a certain amount
ego_start_speed_threshold: null # Limit to scenarios where the ego reaches a certain speed from below
ego_stop_speed_threshold: null # Limit to scenarios where the ego reaches a certain speed from above
speed_noise_tolerance: null # Value at or below which a speed change between two timepoints should be ignored as noise.

expand_scenarios: false
remove_invalid_goals: true
shuffle: false
